name: Build

on:
  push:
    branches: [main]
#   tags:
#     - 'v*.*.*'
jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Release for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pnpm build:pkg

      - name: Release for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          pnpm build:pkg

      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pnpm build:pkg
